M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sun 29 May 2022 07:59:46 PM EDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-05-29T19:59:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X2.3622Y-2.2835
X2.3622Y-9.0551
X5.9843Y-2.2835
X5.9843Y-9.0551
T0
M30
